version: '3.8'

networks:
  video_generation:
    external: true
    name: Video Generation

volumes:
  audio_files:

services:
  video-audio-mixer-api:
    build: .
    networks:
      video_generation:
        ipv4_address: 10.20.0.18
    ports:
      - "8049:8049"
    volumes:
      - /tmp:/tmp
      - audio_files:/app/audio  # Mount audio files volume
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: video-audio-mixer-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8049/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
